import { useState } from 'react';

const AnswerCard = ({ transcript, answer }) => {
  const [displayAnswer, setDisplayAnswer] = useState(answer);
  const [displayTranscript, setDisplayTranscript] = useState(transcript);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // In a real implementation, we would get the answer from the voice recording process
  // For now, we'll simulate it with a button that generates a placeholder answer
  const getAnswer = async () => {
    setLoading(true);
    setError(null);
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000));
      setAnswer("This is a placeholder answer. In a real implementation, this would be generated by the RAG pipeline.");
    } catch (err) {
      setError('Failed to get answer');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      <button
        onClick={getAnswer}
        disabled={loading}
        className={`w-full py-3 px-4 rounded-lg ${
          loading
            ? 'bg-gray-500 cursor-not-allowed'
            : 'bg-blue-500 hover:bg-blue-600 text-white'
        }`}
      >
        {loading ? 'Getting Answer...' : 'Get Answer'}
      </button>
      
      {error && (
        <div className="bg-red-900/50 border border-red-500 text-red-200 px-4 py-3 rounded-lg">
          <p className="font-medium">Error:</p>
          <p className="mt-2">{error}</p>
        </div>
      )}
      
      {!loading && displayAnswer && (
        <div className="bg-gray-800 p-4 rounded-lg">
          {displayTranscript && (
            <div className="mb-2">
              <p className="font-medium">Transcript:</p>
              <p className="mt-1 text-gray-300 whitespace-pre-wrap">{displayTranscript}</p>
            </div>
          )}
          <p className="font-medium">Answer:</p>
          <p className="mt-2 text-gray-300 whitespace-pre-wrap">{displayAnswer}</p>
        </div>
      )}
    </div>
  );
};

export default AnswerCard;